apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsetrace-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulsetrace-backend
  template:
    metadata:
      labels:
        app: pulsetrace-backend
    spec:
      containers:
        - name: backend
          image: pulsetrace_backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsetrace-config
                  key: REDIS_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: pulsetrace-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
